## initializing tensor creation

#### 1. from list

In [1]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"

In [2]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [3]:
my_tensor2 = torch.tensor([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
print(my_tensor2)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


无论是列表还是元组，torch.tensor都会将它们转换为张量，所以my_tensor和my_tensor2的结果是相同的。

In [4]:
print(my_tensor.device)
print(my_tensor2.device)
print(my_tensor.dtype)
my_tensor2 = torch.tensor([(1, 2, 3), (4, 5, 6), (7, 8, 9)],dtype=torch.float32, device=device)
print(my_tensor2.device)
print(my_tensor2.dtype)

cpu
cpu
torch.int64
cpu
torch.float32


### 其他初始化的方法

In [5]:
x = torch.empty(size=(3, 3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
x = torch.zeros((3, 3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [7]:
x = torch.ones((3, 3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [8]:
x = torch.eye(5, 5)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


`torch.eye`创建一个单位矩阵，对角线上的元素为1，其他元素为0

In [9]:
x = torch.rand((3, 3))
print(x)

tensor([[0.9019, 0.2100, 0.8126],
        [0.5526, 0.5354, 0.0305],
        [0.9628, 0.8263, 0.6265]])


In [10]:
x = torch.arange(7)
print(x)
x = torch.arange(1, 7)
print(x)
x = torch.arange(1, 7, 2)
print(x)
x = torch.arange(0, 5, 1)
print(x)
x = torch.arange(start=0, end=5, step=1)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 3, 5])
tensor([0, 1, 2, 3, 4])
tensor([0, 1, 2, 3, 4])


In [11]:
x = torch.linspace(0.1, 1, 10)
print(x)
x = torch.linspace(start=0.1, end = 1, steps=10)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [12]:
x = torch.empty(size=(1, 5))
print(x)
x = x.normal_(mean=0, std=1)
print(x)

tensor([[-1.0185e-23,  1.9016e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[ 1.4993,  1.0666, -0.0791, -0.4129,  1.2724]])


In [13]:
# or
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
print(x)

tensor([[-0.7204, -0.1047,  0.6036,  0.4427, -1.4979]])


In [14]:
# 用区间[0, 1]的均匀分布填充张量
x = torch.empty(size=(1, 5)).uniform_(0, 1)
print(x)

tensor([[0.2142, 0.3811, 0.6197, 0.5289, 0.9761]])


`torch.diag`将一个张量矩阵转为对角矩阵

In [15]:
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


### how to initialize and convert tensors to other types (int, float, double)

In [16]:
tensor = torch.arange(4)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


### Array to Tensor conversion and vice-versa

In [17]:
import numpy as np
np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
np_array_back = tensor.numpy()