## initializing tensor creation

#### 1. from list

In [1]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"

In [5]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [6]:
my_tensor2 = torch.tensor([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
print(my_tensor2)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


无论是列表还是元组，torch.tensor都会将它们转换为张量，所以my_tensor和my_tensor2的结果是相同的。

In [7]:
print(my_tensor.device)
print(my_tensor2.device)
print(my_tensor.dtype)
my_tensor2 = torch.tensor([(1, 2, 3), (4, 5, 6), (7, 8, 9)],dtype=torch.float32, device=device)
print(my_tensor2.device)
print(my_tensor2.dtype)

cpu
cpu
torch.int64
cpu
torch.float32


### 其他初始化的方法

In [8]:
x = torch.empty(size=(3, 3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [9]:
x = torch.zeros((3, 3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [10]:
x = torch.ones((3, 3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [11]:
x = torch.eye(5, 5)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [12]:
x = torch.rand((3, 3))
print(x)

tensor([[0.6798, 0.2548, 0.4269],
        [0.9130, 0.0601, 0.1101],
        [0.9192, 0.9208, 0.9870]])


In [19]:
x = torch.arange(7)
print(x)
x = torch.arange(1, 7)
print(x)
x = torch.arange(1, 7, 2)
print(x)
x = torch.arange(0, 5, 1)
print(x)
x = torch.arange(start=0, end=5, step=1)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 3, 5])
tensor([0, 1, 2, 3, 4])
tensor([0, 1, 2, 3, 4])


In [20]:
x = torch.linspace(0.1, 1, 10)
print(x)
x = torch.linspace(start=0.1, end = 1, steps=10)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [25]:
x = torch.empty(size=(1, 5))
print(x)
x = x.normal_(mean=0, std=1)
print(x)

tensor([[3.3379e-19, 2.0627e-42, 1.2510e+00, 5.6440e-01, 1.2589e+00]])
tensor([[-1.6324, -1.1654, -0.3108,  0.0311, -0.8756]])


In [27]:
# or
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
print(x)

tensor([[-2.2044, -1.0554, -0.4640, -1.4450,  0.3493]])


In [28]:
# 用区间[0, 1]的均匀分布填充张量
x = torch.empty(size=(1, 5)).uniform_(0, 1)
print(x)

tensor([[0.0464, 0.3109, 0.2959, 0.1076, 0.2343]])


In [29]:
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
