### tensor reshaping 

In [1]:
import torch
x = torch.arange(9)
x_3x3 = x.view(3,3)
print(x_3x3)
print(x_3x3.shape)
print(x)
print(x.shape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
torch.Size([3, 3])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
torch.Size([9])


create a new copy of the tensor and don't change the original tensor

In [2]:
x_3x3_1 = x.reshape(3,3)
print(x_3x3_1)
print(x_3x3_1.shape)
print(x)
print(x.shape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
torch.Size([3, 3])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
torch.Size([9])


from above we can see the effect of view and reshape is same. the difference is view is a shallow copy and reshape is a deep copy.总结一下，现在还不用搞懂原理，就是view能干的reshape都能干，但是view不能干的reshape也能干，所以一般用view就行了。

In [3]:
x1 = torch.rand(2,5)
x2 = torch.rand(2,5)
print(torch.cat((x1,x2),dim=0).shape)
print(torch.cat((x1,x2),dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [4]:
z = x1.view(-1)
print(z.shape)

torch.Size([10])


In [5]:
batch = 64
x = torch.rand((batch,2,5))
z = x.view(batch,-1)
print(z.shape)

torch.Size([64, 10])


In [6]:
z = x.permute(0,2,1)
print(z.shape)

torch.Size([64, 5, 2])


转置可以用`.t()`方法，维度更高时用permute函数

In [7]:
x = torch.arange(10)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

torch.Size([1, 10])
torch.Size([10, 1])


In [8]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
print(x.shape)

torch.Size([1, 1, 10])


In [9]:
z = x.squeeze(1)
print(z.shape)

torch.Size([1, 10])
