# Tensor Math and Comparison Operations

In [2]:
import torch
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

# Addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)
print(z1)

tensor([10., 10., 10.])


In [3]:
# or another way
z2 = torch.add(x, y)
print(z2)

tensor([10, 10, 10])


In [4]:
# or another way
z = x + y
print(z)

tensor([10, 10, 10])


### subtraction

In [5]:
z = x - y
print(z)

tensor([-8, -6, -4])


### Division

In [6]:
z = torch.true_divide(x, y)
print(z)

tensor([0.1111, 0.2500, 0.4286])


### Inplace Operations

In [7]:
t = torch.zeros(3)
t.add_(x)
print(t)

tensor([1., 2., 3.])


### Exponential

In [8]:
z = x.pow(2)
print(z)

tensor([1, 4, 9])


In [9]:
z = x ** 2
print(z)

tensor([1, 4, 9])


### Simple Comparison

In [10]:
z = x > 0
print(z)

tensor([True, True, True])


In [11]:
z = x < 0
print(z)

tensor([False, False, False])


### Matrix Multiplication

In [12]:
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2)
print(x3)

tensor([[0.7086, 0.7151, 0.6020],
        [1.9463, 1.1799, 1.9670]])


In [13]:
# or another way
x3 = x1.mm(x2)
print(x3)

tensor([[0.7086, 0.7151, 0.6020],
        [1.9463, 1.1799, 1.9670]])


### Matrix Exponential

In [14]:
matrix_exp = torch.rand(5, 5)
print(matrix_exp)
matrix1 = matrix_exp.matrix_power(3)
print(matrix1)

tensor([[0.0541, 0.7257, 0.5534, 0.3114, 0.6127],
        [0.9282, 0.3048, 0.6456, 0.1153, 0.2675],
        [0.3949, 0.5718, 0.6394, 0.3325, 0.3192],
        [0.9752, 0.6238, 0.5796, 0.4721, 0.7253],
        [0.8617, 0.9915, 0.1393, 0.5835, 0.6890]])
tensor([[3.4907, 3.8478, 3.1643, 2.0547, 3.0808],
        [3.6016, 3.4085, 2.8417, 1.8775, 2.6744],
        [3.4562, 3.6514, 3.0167, 1.9731, 2.8858],
        [5.5816, 5.5947, 4.5573, 3.0443, 4.4462],
        [5.2471, 5.5603, 4.4667, 2.9974, 4.4099]])


### Element wise multiplication

In [15]:
z = x * y
print(z)

tensor([ 9, 16, 21])


In [16]:
# or another way
z = torch.mul(x, y)
print(z)

tensor([ 9, 16, 21])


矩阵乘法的总结：
`*` `torch.mul`、`torch.multiply` 三者操作含义是相同的。只是别名和简写的区别。`torch.multiply` 是 `torch.mul` 的别名，`*` 是 `torch.mul` 的简写。

`torch.mm()`函数用于计算两个矩阵的乘积，但是两个矩阵的维度必须满足矩阵乘法的要求。

`torch.matmul()`函数用于计算两个张量的乘积，但是两个张量的维度必须满足广播的要求。


### Dot Product

In [17]:
z = torch.dot(x, y)
print(z)
#or another way
z = x.dot(y)
print(z)

tensor(46)
tensor(46)


在用`torch.dot()`时要注意这个函数用于计算两个一维张量的点积。对于更高维的张量，可以使用`torch.matmul()`函数。
而且两个张量的维度必须相同，且张量的元素个数也必须相同。

### Batch Matrix Multiplication

In [18]:
batch = 32
n = 10
m = 20
p = 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)

在这个例子中：

tensor1 的形状是 (batch, n, m)，即 (32, 10, 20)。它表示有 32 个 10x20 的矩阵。
tensor2 的形状是 (batch, m, p)，即 (32, 20, 30)。它表示有 32 个 20x30 的矩阵。
torch.bmm(tensor1, tensor2) 的操作是对这 32 对矩阵分别进行矩阵乘法操作。对于每个 i (0 <= i < 32)，计算 tensor1[i] 和 tensor2[i] 的矩阵乘积。

### examples of boardcasting

In [19]:
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))

z = x1 - x2


In [20]:
print(z)

tensor([[ 0.3134, -0.7650,  0.0216, -0.1860,  0.4656],
        [ 0.3192, -0.5833,  0.4658, -0.0076,  0.3512],
        [-0.3568, -0.7488,  0.5980, -0.6667,  0.1463],
        [ 0.3745, -0.3787,  0.8744, -0.6054,  0.7659],
        [-0.0203, -0.8447,  0.9403,  0.0239,  0.0819]])


### other useful tensor operations

In [21]:
x_to_sum = torch.rand((5, 2, 3))
print(x_to_sum)

tensor([[[0.5878, 0.8896, 0.7794],
         [0.5391, 0.2126, 0.0734]],

        [[0.4254, 0.5586, 0.6206],
         [0.0324, 0.6282, 0.5655]],

        [[0.5419, 0.8184, 0.5185],
         [0.4072, 0.1345, 0.1188]],

        [[0.5047, 0.9791, 0.0626],
         [0.7169, 0.3122, 0.2491]],

        [[0.5733, 0.9617, 0.3749],
         [0.1766, 0.9617, 0.7311]]])


In [22]:
sum_over_batch = torch.sum(x_to_sum, dim = 0)
print(sum_over_batch)

tensor([[2.6329, 4.2074, 2.3560],
        [1.8722, 2.2492, 1.7380]])


In [23]:
sum_over_n = torch.sum(x_to_sum, dim = 1)
print(sum_over_n)

tensor([[1.1269, 1.1022, 0.8529],
        [0.4578, 1.1868, 1.1861],
        [0.9490, 0.9529, 0.6373],
        [1.2215, 1.2912, 0.3117],
        [0.7499, 1.9234, 1.1060]])


In [24]:
sum_over_m = torch.sum(x_to_sum, dim = 2)
print(sum_over_m)

tensor([[2.2568, 0.8251],
        [1.6046, 1.2262],
        [1.8788, 0.6605],
        [1.5463, 1.2781],
        [1.9099, 1.8694]])


In [25]:
total_sum = torch.sum(x_to_sum)
print(total_sum)

tensor(15.0557)


#### max

In [26]:
x = torch.rand(2, 5)
print(x)

tensor([[0.0704, 0.6303, 0.0136, 0.4029, 0.7298],
        [0.7980, 0.2494, 0.1617, 0.7156, 0.5192]])


In [27]:
values, indices = torch.max(x, dim = 0)
print(values, indices)

tensor([0.7980, 0.6303, 0.1617, 0.7156, 0.7298]) tensor([1, 0, 1, 1, 0])


In [28]:
values, indices = torch.max(x, dim = 1)
print(values, indices)

tensor([0.7298, 0.7980]) tensor([4, 0])


In [29]:
print(x)
values, indices = torch.min(x, dim = 0)
print(values, indices)

tensor([[0.0704, 0.6303, 0.0136, 0.4029, 0.7298],
        [0.7980, 0.2494, 0.1617, 0.7156, 0.5192]])
tensor([0.0704, 0.2494, 0.0136, 0.4029, 0.5192]) tensor([0, 1, 0, 0, 1])


#### abs

In [30]:
x = torch.linspace(-10, 10, 10)
print(x)
abs_x = torch.abs(x)
print(abs_x)

tensor([-10.0000,  -7.7778,  -5.5556,  -3.3333,  -1.1111,   1.1111,   3.3333,
          5.5556,   7.7778,  10.0000])
tensor([10.0000,  7.7778,  5.5556,  3.3333,  1.1111,  1.1111,  3.3333,  5.5556,
         7.7778, 10.0000])


In [31]:
z = torch.argmax(x)
print(z)

tensor(9)


#### mean

In [32]:
print(x)
mean_x = torch.mean(x.float(), dim = 0)
print(mean_x)

tensor([-10.0000,  -7.7778,  -5.5556,  -3.3333,  -1.1111,   1.1111,   3.3333,
          5.5556,   7.7778,  10.0000])
tensor(9.5367e-08)


In [34]:
x = torch.rand(2, 5)
mean_x_1 = torch.mean(x.float(), dim = 1)
print(mean_x_1)

tensor([0.5867, 0.3615])


#### clamp

In [35]:
x = torch.arange(-5, 15, 2)
print(x)

tensor([-5, -3, -1,  1,  3,  5,  7,  9, 11, 13])


In [36]:
x_clamp = x.clamp(min = 0)
print(x_clamp)

tensor([ 0,  0,  0,  1,  3,  5,  7,  9, 11, 13])


In [37]:
x_clamp = x.clamp(max = 10)
print(x_clamp)

tensor([-5, -3, -1,  1,  3,  5,  7,  9, 10, 10])


In [38]:
x_clamp = x.clamp(min = 0, max = 10)
print(x_clamp)

tensor([ 0,  0,  0,  1,  3,  5,  7,  9, 10, 10])


torch.any 可以测试张量中是否有任意元素为真。
如果不指定维度，它将返回一个标量，表示整个张量中是否有任意元素为真。
如果指定维度，它将沿着该维度操作，返回一个新的张量，表示每一行或每一列是否有任意元素为真。

In [39]:
# 创建一个张量
x = torch.tensor([[0, 0, 0], [1, 0, 0], [0, 0, 1]])
print("Original tensor x:\n", x)

# 沿着第 0 维度（行）进行操作
any_true_dim0 = torch.any(x, dim=0)
print("Any element is true along dim 0:\n", any_true_dim0)

# 沿着第 1 维度（列）进行操作
any_true_dim1 = torch.any(x, dim=1)
print("Any element is true along dim 1:\n", any_true_dim1)

Original tensor x:
 tensor([[0, 0, 0],
        [1, 0, 0],
        [0, 0, 1]])
Any element is true along dim 0:
 tensor([ True, False,  True])
Any element is true along dim 1:
 tensor([False,  True,  True])


In [40]:
all_true_dim0 = torch.all(x, dim=0)
print("All elements are true along dim 0:\n", all_true_dim0)
all_true_dim1 = torch.all(x, dim=1)
print("All elements are true along dim 1:\n", all_true_dim1)


All elements are true along dim 0:
 tensor([False, False, False])
All elements are true along dim 1:
 tensor([False, False, False])
