# Tensor Math and Comparison Operations

In [1]:
import torch
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

# Addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)
print(z1)

tensor([10., 10., 10.])


In [2]:
# or another way
z2 = torch.add(x, y)
print(z2)

tensor([10, 10, 10])


In [3]:
# or another way
z = x + y
print(z)

tensor([10, 10, 10])


### subtraction

In [4]:
z = x - y
print(z)

tensor([-8, -6, -4])


### Division

In [5]:
z = torch.true_divide(x, y)
print(z)

tensor([0.1111, 0.2500, 0.4286])


### Inplace Operations

In [6]:
t = torch.zeros(3)
t.add_(x)
print(t)

tensor([1., 2., 3.])


### Exponential

In [7]:
z = x.pow(2)
print(z)

tensor([1, 4, 9])


In [8]:
z = x ** 2
print(z)

tensor([1, 4, 9])


### Simple Comparison

In [9]:
z = x > 0
print(z)

tensor([True, True, True])


In [10]:
z = x < 0
print(z)

tensor([False, False, False])


### Matrix Multiplication

In [11]:
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2)
print(x3)

tensor([[0.8929, 1.3297, 0.6892],
        [0.6320, 1.0509, 1.2979]])


In [12]:
# or another way
x3 = x1.mm(x2)
print(x3)

tensor([[0.8929, 1.3297, 0.6892],
        [0.6320, 1.0509, 1.2979]])


### Matrix Exponential

In [14]:
matrix_exp = torch.rand(5, 5)
print(matrix_exp)
matrix1 = matrix_exp.matrix_power(3)
print(matrix1)

tensor([[0.7776, 0.7692, 0.8097, 0.7730, 0.6077],
        [0.1657, 0.9350, 0.4295, 0.2274, 0.4279],
        [0.9458, 0.9808, 0.0968, 0.5220, 0.8759],
        [0.1016, 0.2652, 0.7032, 0.7387, 0.5517],
        [0.9063, 0.4234, 0.6333, 0.2926, 0.2145]])
tensor([[6.0129, 7.3637, 5.6972, 5.2998, 5.6348],
        [3.1643, 4.0825, 3.0001, 2.7097, 2.9723],
        [5.3808, 6.6876, 4.8003, 4.7078, 5.1755],
        [3.6881, 4.3904, 3.5212, 3.2551, 3.3909],
        [4.2987, 5.2880, 4.1650, 3.8275, 4.0279]])


### Element wise multiplication

In [15]:
z = x * y
print(z)

tensor([ 9, 16, 21])


In [16]:
# or another way
z = torch.mul(x, y)
print(z)

tensor([ 9, 16, 21])


矩阵乘法的总结：
`*` `torch.mul`、`torch.multiply` 三者操作含义是相同的。只是别名和简写的区别。`torch.multiply` 是 `torch.mul` 的别名，`*` 是 `torch.mul` 的简写。

`torch.mm()`函数用于计算两个矩阵的乘积，但是两个矩阵的维度必须满足矩阵乘法的要求。

`torch.matmul()`函数用于计算两个张量的乘积，但是两个张量的维度必须满足广播的要求。


### Dot Product

In [17]:
z = torch.dot(x, y)
print(z)
#or another way
z = x.dot(y)
print(z)

tensor(46)
tensor(46)


在用`torch.dot()`时要注意这个函数用于计算两个一维张量的点积。对于更高维的张量，可以使用`torch.matmul()`函数。
而且两个张量的维度必须相同，且张量的元素个数也必须相同。

### Batch Matrix Multiplication